variables:
  ORD_SOUMET_SHELL: "/bin/bash"
  ORD_SOUMET_CPUS: "40"
  ORD_SOUMET_TMPFS: "8G"
  ORD_SOUMET_M: "80G"
  ORD_SOUMET_W: "10"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - package
  - deploy

before_script:
    - export CLICOLOR_FORCE=1

build:XC50_intel-19.0.5:
  stage: build
  tags:
  - XC50-login
  when: always
  script:
    - set +e
    - source ci-env/latest/sles-15-skylake-64/intel-19.0.5.281.sh
    - mkdir build_XC50_intel-19.0.5
    - cd build_XC50_intel-19.0.5
    - cmake ..
    - make -j `nproc`
  artifacts:
    expire_in: 2 hrs
    paths:
    - build_XC50_intel-19.0.5

build:intel-19.0.3:
  stage: build
  when: always
  script:
    - source ci-env/latest/ubuntu-18.04-skylake-64/intel-19.0.3.199.sh
    - mkdir build_intel-19.0.3
    - cd build_intel-19.0.3
    - cmake ..
    - make -j `nproc`
  artifacts:
    expire_in: 2 hrs
    paths:
    - build_intel-19.0.3

build:gnu-7.4.0:
  stage: build
  when: always
  script:
    - source ci-env/latest/ubuntu-18.04-amd-64/gnu-7.4.0.sh
    - mkdir build_gnu-7.4
    - cd build_gnu-7.4
    - cmake ..
    - make -j `nproc`
  artifacts:
    expire_in: 2 hrs
    paths:
    - build_gnu-7.4

build:gnu-7.5.0:
  stage: build
  when: always
  script:
    - source ci-env/latest/ubuntu-18.04-amd-64/gnu-7.5.0.sh
    - mkdir build_gnu-7.5
    - cd build_gnu-7.5
    - cmake ..
    - make -j `nproc`
  artifacts:
    expire_in: 2 hrs
    paths:
    - build_gnu-7.5

build:gnu-9.3:
  stage: build
  when: always
  script:
    - source ci-env/latest/ubuntu-18.04-amd-64/gnu-9.3.0.sh
    - mkdir build_gnu-9.3
    - cd build_gnu-9.3
    - cmake ..
    - make -j `nproc`
  artifacts:
    expire_in: 2 hrs
    paths:
    - build_gnu-9.3

package:XC50_intel-19.0.5:
   stage: package
#   only:
#      - tags
   dependencies:
      - build:XC50_intel-19.0.5
   environment:
      name: testing
   script:
      - source ci-env/latest/sles-15-skylake-64/intel-19.0.5.281.sh
      - cd build_XC50_intel-19.0.5
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package

package:intel-19.0.3:
   stage: package
#   only:
#      - tags
   dependencies:
      - build:intel-19.0.3
   environment:
      name: testing
   script:
      - source ci-env/latest/ubuntu-18.04-skylake-64/intel-19.0.3.199.sh
      - cd build_intel-19.0.3
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package

package:gnu-7.4.0:
   stage: package
#   only:
#      - tags
   dependencies:
      - build:gnu-7.4.0
   environment:
      name: testing
   script:
      - source ci-env/latest/ubuntu-18.04-amd-64/gnu-7.4.0.sh
      - cd build_gnu-7.4.0
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package
      
deploy:staging:
   stage: deploy
#   only:
#      - tags
   script:
      - source ci-env/latest/profile.sh
      - ~/ci-admin-bundle/bin/ci-stage-ssm.sh libs $CI_PROJECT_NAME $CI_COMMIT_TAG
